const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#year').textContent=new Date().getFullYear();
function renderProjects(){ $('#projectsGrid').innerHTML=featuredProjects.map(p=>`<article class="project reveal"><div class="project-img"><span>${p.number}</span><div class="mockup"><div></div><div></div><div></div></div></div><div class="project-body"><h3>${p.title}</h3><small>${p.type}</small><p>${p.description}</p><div class="tags">${p.tech.map(x=>`<span>${x}</span>`).join('')}</div><a href="${p.url}" target="_blank" aria-label="Open ${p.title} on GitHub">↗</a></div></article>`).join('');}
function renderCerts(){ $('#certList').innerHTML=certifications.map((c,i)=>`<div class="cert-item reveal"><span class="cert-icon">${c.icon}</span><div><b>${c.title}</b><small>${c.issuer}</small></div><strong class="${c.status==='In Progress'?'pending':''}">${c.status}</strong></div>`).join(''); }
async function repos(){const box=$('#repos');try{const r=await fetch('https://api.github.com/users/Jaweriaharoon29/repos?sort=updated&per_page=3');if(!r.ok)throw 0;const data=await r.json();box.innerHTML=data.map(x=>`<a class="repo reveal" href="${x.html_url}" target="_blank"><div><b>${x.name}</b><span>Public</span></div><p>${esc(x.description||'Public project from Jaweria Haroon')}</p><small>★ ${x.stargazers_count}　◉ ${x.language||'Code'}</small></a>`).join('');observe();}catch(e){box.innerHTML='<div class="repo-loading">GitHub is temporarily unavailable. <a href="https://github.com/Jaweriaharoon29" target="_blank">Open profile →</a></div>';}}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));}
const menu=$('#menu'),nav=$('#navLinks');menu.onclick=()=>nav.classList.toggle('open');$$('.nav-links a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
window.addEventListener('scroll',()=>{$('#header').classList.toggle('scrolled',scrollY>25);const m=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=(scrollY/m*100)+'%';});
const glow=$('.cursor-glow');window.addEventListener('pointermove',e=>{if(innerWidth>900){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
renderProjects();renderCerts();repos();observe();
